<script lang="ts">
	import { toast } from 'svelte-sonner';

	import { createEventDispatcher, onMount, getContext } from 'svelte';
	import { config, models } from '$lib/stores';
	import Tags from '$lib/components/common/Tags.svelte';
	import XMark from '$lib/components/icons/XMark.svelte';

	const i18n = getContext('i18n');

	const dispatch = createEventDispatcher();

	export let message;
	export let show = false;

	let LIKE_REASONS = [
		'accurate_information',
		'followed_instructions_perfectly',
		'showcased_creativity',
		'positive_attitude',
		'attention_to_detail',
		'thorough_explanation',
		'other'
	];
	let DISLIKE_REASONS = [
		'dont_like_the_style',
		'too_verbose',
		'not_helpful',
		'not_factually_correct',
		'didnt_fully_follow_instructions',
		'refused_when_it_shouldnt_have',
		'being_lazy',
		'other'
	];

	let tags = [];

	let reasons = [];
	let selectedReason = null;
	let comment = '';

	let detailedRating = null;
	let selectedModel = null;

	$: if (message?.annotation?.rating === 1) {
		reasons = LIKE_REASONS;
	} else if (message?.annotation?.rating === -1) {
		reasons = DISLIKE_REASONS;
	}

	$: if (message) {
		init();
	}

	const init = () => {
		if (!selectedReason) {
			selectedReason = message?.annotation?.reason ?? '';
		}

		if (!comment) {
			comment = message?.annotation?.comment ?? '';
		}

		tags = (message?.annotation?.tags ?? []).map((tag) => ({
			name: tag
		}));

		if (!detailedRating) {
			detailedRating = message?.annotation?.details?.rating ?? null;
		}
	};

	onMount(() => {
		if (message?.arena) {
			selectedModel = $models.find((m) => m.id === message.selectedModelId);
			toast.success(
				$i18n.t('This response was generated by "{{model}}"', {
					model: selectedModel ? (selectedModel?.name ?? selectedModel.id) : message.selectedModelId
				})
			);
		}
	});

	const saveHandler = () => {
		console.log('saveHandler');
		// if (!selectedReason) {
		// 	toast.error($i18n.t('Please select a reason'));
		// 	return;
		// }

		dispatch('save', {
			reason: selectedReason,
			comment: comment,
			tags: tags.map((tag) => tag.name),
			details: {
				rating: detailedRating
			}
		});

		toast.success($i18n.t('Thanks for your feedback!'));
		show = false;
	};
</script>

{#if message?.arena}
	<div style="--size:0.75rem; --weight:500; --pt:0.375rem; --mb:-0.125rem">
		{$i18n.t('This response was generated by "{{model}}"', {
			model: selectedModel ? (selectedModel?.name ?? selectedModel.id) : message.selectedModelId
		})}
	</div>
{/if}

<div
	style="--my:0.625rem; --radius:0.75rem; --px:1rem; --py:0.75rem; --b:1px solid; --bc:var(--color-gray-100); --dark-bc:var(--color-gray-850)"
	id="message-feedback-{message.id}"
>
	<div style="--d:flex; --jc:space-between; --ai:center">
		<div style="--size:0.875rem; --weight:500">{$i18n.t('How would you rate this response?')}</div>

		<!-- <div style="--size:0.875rem">{$i18n.t('Tell us more:')}</div> -->

		<button
			on:click={() => {
				show = false;
			}}
		>
			<XMark className={'size-4'} />
		</button>
	</div>

	<div style="--w:100%; --d:flex; --jc:center">
		<div style="--pos:relative; --w:fit-content; --ofx:auto"
	class="scrollbar-none">
			<div style="--mt:0.375rem; --w:fit-content; --d:flex; --g:0.25rem; --pb:0.5rem">
				<!-- 1-10 scale -->
				{#each Array.from({ length: 10 }).map((_, i) => i + 1) as rating}
					<button
						style="--w:1.75rem; --h:1.75rem; --size:0.875rem; --b:1px solid; --bc:var(--color-gray-100); --dark-bc:var(--color-gray-850); --hvr-bgc:var(--color-gray-50); --hvr-dark-bgc:var(--color-gray-850); --tn:color, background-color, border-color, text-decoration-color, fill, stroke, opacity, box-shadow, transform, filter, backdrop-filter 150ms cubic-bezier(0.4, 0, 0.2, 1); --radius:9999px"
	class="{detailedRating ===
						rating
							? 'bg-gray-100 dark:bg-gray-800'
							: ''} disabled:cursor-not-allowed disabled:text-gray-500 disabled:bg-white dark:disabled:bg-gray-900"
						on:click={() => {
							detailedRating = rating;
						}}
						disabled={message?.annotation?.rating === -1 ? rating > 5 : rating < 6}
					>
						{rating}
					</button>
				{/each}
			</div>

			<div style="--pos:sticky; --top:0; --bottom:0; --left:0; --right:0; --d:flex; --jc:space-between; --size:0.75rem">
				<div>
					1 - {$i18n.t('Awful')}
				</div>

				<div>
					10 - {$i18n.t('Amazing')}
				</div>
			</div>
		</div>
	</div>

	<div>
		{#if reasons.length > 0}
			<div style="--size:0.875rem; --mt:0.375rem; --weight:500">{$i18n.t('Why?')}</div>

			<div style="--d:flex; --fw:wrap; --g:0.375rem; --size:0.875rem; --mt:0.375rem">
				{#each reasons as reason}
					<button
						style="--px:0.75rem; --py:0.125rem; --b:1px solid; --bc:var(--color-gray-100); --dark-bc:var(--color-gray-850); --hvr-bgc:var(--color-gray-50); --hvr-dark-bgc:var(--color-gray-850); --tn:color, background-color, border-color, text-decoration-color, fill, stroke, opacity, box-shadow, transform, filter, backdrop-filter 150ms cubic-bezier(0.4, 0, 0.2, 1); --radius:0.75rem"
	class="{selectedReason ===
						reason
							? 'bg-gray-100 dark:bg-gray-800'
							: ''}"
						on:click={() => {
							selectedReason = reason;
						}}
					>
						{#if reason === 'accurate_information'}
							{$i18n.t('Accurate information')}
						{:else if reason === 'followed_instructions_perfectly'}
							{$i18n.t('Followed instructions perfectly')}
						{:else if reason === 'showcased_creativity'}
							{$i18n.t('Showcased creativity')}
						{:else if reason === 'positive_attitude'}
							{$i18n.t('Positive attitude')}
						{:else if reason === 'attention_to_detail'}
							{$i18n.t('Attention to detail')}
						{:else if reason === 'thorough_explanation'}
							{$i18n.t('Thorough explanation')}
						{:else if reason === 'dont_like_the_style'}
							{$i18n.t("Don't like the style")}
						{:else if reason === 'too_verbose'}
							{$i18n.t('Too verbose')}
						{:else if reason === 'not_helpful'}
							{$i18n.t('Not helpful')}
						{:else if reason === 'not_factually_correct'}
							{$i18n.t('Not factually correct')}
						{:else if reason === 'didnt_fully_follow_instructions'}
							{$i18n.t("Didn't fully follow instructions")}
						{:else if reason === 'refused_when_it_shouldnt_have'}
							{$i18n.t("Refused when it shouldn't have")}
						{:else if reason === 'being_lazy'}
							{$i18n.t('Being lazy')}
						{:else if reason === 'other'}
							{$i18n.t('Other')}
						{:else}
							{reason}
						{/if}
					</button>
				{/each}
			</div>
		{/if}
	</div>

	<div style="--mt:0.5rem">
		<textarea
			bind:value={comment}
			style="--w:100%; --size:0.875rem; --px:0.25rem; --py:0.5rem; --bgc:transparent; --oe:none; resize:none; --radius:0.75rem"
			placeholder={$i18n.t('Feel free to add specific details')}
			rows="3"
		/>
	</div>

	<div style="--mt:0.5rem; --g:0.375rem; --d:flex; --jc:space-between">
		<div style="--d:flex; --ai:flex-end"
	class="group">
			<Tags
				{tags}
				on:delete={(e) => {
					tags = tags.filter(
						(tag) =>
							tag.name.replaceAll(' ', '_').toLowerCase() !==
							e.detail.replaceAll(' ', '_').toLowerCase()
					);
				}}
				on:add={(e) => {
					tags = [...tags, { name: e.detail }];
				}}
			/>
		</div>

		<button
			style="--px:0.875rem; --py:0.375rem; --size:0.875rem; --weight:500; --bgc:#000; --hvr-bgc:var(--color-gray-900); --c:#fff; --dark-bgc:#fff; --dark-c:#000; --hvr-dark-bgc:var(--color-gray-100); --tn:color, background-color, border-color, text-decoration-color, fill, stroke, opacity, box-shadow, transform, filter, backdrop-filter 150ms cubic-bezier(0.4, 0, 0.2, 1); --radius:9999px"
			on:click={() => {
				saveHandler();
			}}
		>
			{$i18n.t('Save')}
		</button>
	</div>
</div>
